### ISSUE TITLE
Can stemcells/releases be URLs?

### ISSUE THREAD

**Issue by drnic** [concourse/bosh-deployment-resource#1]
Does this resource require fully downloaded stemcells/releases? Or is there a way to pass in URLs to these assets uploaded to s3/somewhere (which `bosh upload [release|stemcell] URL` can support)?

**Comment by vito** [comment]
Not implemented at the moment. Currently it only supports uploading tarballs directly. I've labelled a related story that we already had to keep track of this.

**Comment by chendrix** [comment]
:+1:

**Comment by chendrix** [comment]
Hi there!

This resource is being deprecated in favor of https://github.com/cloudfoundry/bosh-deployment-resource, so I'm closing out all existing issues.

Thanks again for your involvement!
