### ISSUE TITLE
Bosh resource occasionally fails to replace director_uuid in manifest

### ISSUE THREAD

**Issue by ljfranklin** [concourse/bosh-deployment-resource#10]
In our manifest we set `director_uuid: null` and rely on the resource to set the value to the correct UUID. 

We've run several hundred bosh deployments perfectly fine, but we just had the following error when `put`ting to the resource:

```
Invalid manifest `bosh_manifest20150901-11-1b9tfq4': name and director UUID are required
```

Re-running the job succeeded. @robdimsdale may have seen the same error.

**Comment by robdimsdale** [comment]
yes I saw this once in concourse's own pipeline (deploying to bosh-lite in testflight). I thought it highly suspect so I re-ran the build and saw it succeed the second time.

**Comment by chendrix** [comment]
Hi there!

This resource is being deprecated in favor of https://github.com/cloudfoundry/bosh-deployment-resource, so I'm closing out all existing issues.

Thanks again for your involvement!
