### ISSUE TITLE
Input action to download manifest?

### ISSUE THREAD

**Issue by rosenhouse** [concourse/bosh-deployment-resource#11]
We have some interest in an "in" action that would drop the manifest for the current deployment as a file, for subsequent parsing / use.

Any reason this wouldn't work / we shouldn't look into it?

**Comment by vito** [comment]
Yep this is what we want `in` to do, just haven't gotten around to it.

**Comment by DanielJonesEB** [comment]
We've got a use case where we'd like to be able to get IP addresses out for a deployment, so we can refer to them in a subsequent Terraform `put`. Hence getting both the manifest and the JSON output of `bosh-cli instances` would be handy.

@vito Is there any merit in the latter? Should I raise that as a separate issue? I'm on billable time for a customer at the moment, but it might be something someone from EngineerBetter can look at.

**Comment by chendrix** [comment]
Hi there!

This resource is being deprecated in favor of https://github.com/cloudfoundry/bosh-deployment-resource, so I'm closing out all existing issues.

Thanks again for your involvement!
