### ISSUE TITLE
use --redact-diff when deploying

### ISSUE THREAD

**Issue by robdimsdale** [concourse/bosh-deployment-resource#15]
When bosh deploying, we like to use `--redact-diff` to avoid leaking passwords etc. This resource should support that.

It could be mandatory, which is really easy (add `--redact-diff` to https://github.com/concourse/bosh-deployment-resource/blob/master/lib/bosh_deployment_resource/bosh.rb#L22) or it could be optional, which is a little harder.

I would happily submit a PR for the former, I'm less interested in the latter - the only use-case I could see is when debugging a failed deploy, and for that we can interact with bosh directly.

**Comment by longnguyen11288** [comment]
:+1: can we do this by default?

**Comment by jszroberto** [comment]
Was this ever implemented? 

I am getting redacted everywhere

**Comment by robdimsdale** [comment]
This was implemented in the BOSH CLI and incorporated into the resource when the CLI was bumped. I'll close this issue now.
