### ISSUE TITLE
Successful deploy but failed resource

### ISSUE THREAD

**Issue by drnic** [concourse/bosh-deployment-resource#2]
I have a normal micro bosh on aws and I deployed a normal manifest. The bosh deployment task succeeded; but the concourse `put` resource failed:

```
Deployed `bosh_manifest20150411-22-v5ddgx' to `https://54.149.109.239:25555'
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
resource script '/opt/resource/out [/tmp/build/src]' failed: exit status 1
```

a) what part of the stack is trying to use "POODLE" SSLv3?
b) does anyone else get this error?
c) should `ignore_ssl` be true for all default bosh, unless you setup a custom SSL cert?

**Comment by vito** [comment]
a) The version of ruby baked into the image appears to use it, but I'm not sure if that's a huge deal.

b) Yes, if you don't have `ignore_ssl` set to true and have an untrusted/self-signed cert in front of the director, which is most cases.

c) We'll probably instead change this to stick to the `bosh` CLI which doesn't have these issues. We hit the director API ourselves after the deploy to determine the version, but the downside is we have to implement our own client logic. If we can stick to `bosh` commands this problem wouldn't appear. I've tagged the (already-existing) story with this issue to keep them in sync.
