### ISSUE TITLE
Docs are wrong

### ISSUE THREAD

**Issue by jhiemer** [concourse/bosh-deployment-resource#28]
With the docs here https://concourse.ci/deploying-concourse.html the deployment fails. 

Removing this line:
```yml
  vm_extensions:
  - large
```

for the worker and adding:

`persistent_disk_type: large`

leads to a successful deployment.

**Comment by vito** [comment]
I don't see the line you're referencing. The docs look fine to me.

**Comment by jhiemer** [comment]
No they are not. Take a look at the screenshot, there you can see what I have referenced. 

<img width="889" alt="screen shot 2016-07-18 at 20 46 04" src="https://cloud.githubusercontent.com/assets/1557826/16926411/caad6b28-4d28-11e6-8bc0-b06d15a412f2.png">

**Comment by vito** [comment]
Can you elaborate why it doesn't work or submit a PR?
