### ISSUE TITLE
package cache

### ISSUE THREAD

**Issue by sax** [concourse/bosh-deployment-resource#29]
It would be great if I could save off the compiled packages after each run, either to a volume within Concourse or to S3. I am using this resource to deploy CloudFoundry to a bosh-lite in AWS that I tear down between job runs. Even when only my own component changes, I have to wait for about 40 minutes in each run for packages to compile.

If this resource could be configured to persist the compiled packages, then we might be able to shave off around 30 minutes of these job runs.

I'm not sure where I would begin with a pull request, or if this is possible through some other clever mechanism.

**Comment by chendrix** [comment]
Hi there!

This resource is being deprecated in favor of https://github.com/cloudfoundry/bosh-deployment-resource, so I'm closing out all existing issues.

Thanks again for your involvement!
