### ISSUE TITLE
deployment name in source versus manifest

### ISSUE THREAD

**Issue by mmb** [concourse/bosh-deployment-resource#32]
The resource currently compares the deployment name in the source configuration and the one in the manifest. It errors if they do not agree.

Would it be possible to treat the source configuration as authoritative and inject it into the manifest before deployment?

**Comment by chendrix** [comment]
Hi there!

This resource is being deprecated in favor of https://github.com/cloudfoundry/bosh-deployment-resource, so I'm closing out all existing issues.

Thanks again for your involvement!
