### ISSUE TITLE
Why use the bosh cli rather than the bosh api?

### ISSUE THREAD

**Issue by simonjohansson** [concourse/bosh-deployment-resource#4]
Just curious.

**Comment by vito** [comment]
The bosh director API is not intended for external use (it just happens to be kind of stable). The bosh CLI is the only thing we should really be using. Also means we don't have to invent our own way of rendering e.g. task output; using the CLI will have familiar UX to folks used to BOSH.

We have to dig into the API directly in one place though which isn't great.

**Comment by simonjohansson** [comment]
Okok, good to know, thanks!

Ive build all my automation around the bosh api :(
