### ISSUE TITLE
Absence of stacktraces leads to difficult-to-debug problems

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/bosh-deployment-resource#42]
Currently, [`bdr_out`](https://github.com/concourse/bosh-deployment-resource/blob/1e10cd8603022788e657de7655057a219a8b28c2/bin/bdr_out#L38-L40) will emit a log line for an exception. But it does not emit a stack trace.

Supposing you get this:

```
undefined method `fetch' for #<String:0x00000000f98fa8>`
```

`fetch` is referred to more than a dozen times in the source code. It is difficult to work out which instance is at fault.

We suggest adding this line:

`  STDERR.puts e.backtrace.join("\n")`

So that stacktraces appear as well. In our case we would have been able to zero in much faster on [our underlying problem](https://github.com/concourse/bosh-deployment-resource/issues/35#issuecomment-276103235). As it is, we wound up editing the resource *in situ* to add this line.

**Comment by chendrix** [comment]
Hi there!

This resource is being deprecated in favor of https://github.com/cloudfoundry/bosh-deployment-resource, so I'm closing out all existing issues.

Thanks again for your involvement!
