### ISSUE TITLE
Cancelling the Concourse build should cancel the bosh task

### ISSUE THREAD

**Issue by pronoiac** [concourse/bosh-deployment-resource#43]
Feature request / bug report -
I expected cancelling the Concourse build to cancel the bosh task. I might be misremembering, but I thought it used to do this.

**Comment by chendrix** [comment]
Hi there!

This resource is being deprecated in favor of https://github.com/cloudfoundry/bosh-deployment-resource, so I'm closing out all existing issues.

Thanks again for your involvement!
