### ISSUE TITLE
Any thoughts on supporting runtime and cloud configs?

### ISSUE THREAD

**Issue by skibum55** [concourse/bosh-deployment-resource#44]
As a platform operator
I need to use bosh addons to install components on all my jobs across deployments
So that I can comply with regulatory requirements

As a platform operator
I need to update instance types in my cloud config
So that I can deprecate end of life types.

**Comment by chendrix** [comment]
This resource is being deprecated in favor of https://github.com/cloudfoundry/bosh-deployment-resource, so we are unlikely to add any new features.

We appreciate the level of involvement!
