### ISSUE TITLE
undefined method `fetch' for #<String:0x00000001535088>

### ISSUE THREAD

**Issue by gerhard** [concourse/bosh-deployment-resource#45]
We have a bosh-deployment put resource which is failing with `undefined method 'fetch' for #<String:0x00000001535088>`. This error doesn't give us enough information to pinpoint the actual error. How can we find the real reason for the failure?

cc @dumbbell

**Comment by chendrix** [comment]
We are in the process of deprecating this resource in favor of https://github.com/cloudfoundry/bosh-deployment-resource

**Comment by gerhard** [comment]
Thank you for confirming this.
