### ISSUE TITLE
Add support for recreate

### ISSUE THREAD

**Issue by Nopik** [concourse/bosh-deployment-resource#5]
Basically a equivalent of

```
bosh deploy --recreate
```

**Comment by mariash** [comment]
@Nopik please provide more details. In which case resource should use recreate?

**Comment by chendrix** [comment]
Hi there!

This resource is being deprecated in favor of https://github.com/cloudfoundry/bosh-deployment-resource, so I'm closing out all existing issues.

Thanks again for your involvement!
