### ISSUE TITLE
Invalid manifest generated

### ISSUE THREAD

**Issue by robdimsdale** [concourse/bosh-deployment-resource#7]
When running a bosh deployment we received the following error when trying to deploy:

```
Release uploaded
Invalid manifest `bosh_manifest20150806-10-srhfen': name and director UUID are required
Processing deployment manifest
------------------------------
Getting deployment properties from director...
Compiling deployment manifest...

command 'bosh -n --color -t 10.0.19.254 -d /tmp/bosh_manifest20150806-10-srhfen deploy' failed!
```

/CC @tobocop

**Comment by xoebus** [comment]
Never seen this before.

Was there anything strange about the manifest?

**Comment by robdimsdale** [comment]
no, we re-ran the build (with no new resources) and it worked just fine the second time. It could be something like a bad file handle when copying the resource over. We didn't `intercept` the container so we don't know what was going on.

From my perspective I'm happy to close this issue as it's not reproducible, and there's no obvious action to take. @vito and @tobocop saw this and didn't have any thoughts at the time. At least we have a record of it happening if it happens again.

**Comment by xoebus** [comment]
Yeah, if it happens again then seeing what the resulting manifest was would make debugging this a lot easier.
